- type: entity
  name: stun baton double
  parent: [BaseItem, BaseRestrictedContraband]
  id: StunbatonDouble
  description: A stun baton for incapacitating people with. Actively harming with this is considered bad tone.
  components:
  - type: Sprite
    sprite: _CorvaxNext/Objects/Weapons/Melee/double_stunbaton.rsi
    layers:
    - state: double_stunbaton_off
      map: [ "enum.ToggleVisuals.Layer" ]
  - type: Stunbaton
    energyPerUse: 50
  - type: ItemToggle
    predictable: false
    soundActivate:
      collection: sparks
      params:
        variation: 0.250
    soundDeactivate:
      collection: sparks
      params:
        variation: 0.250
    soundFailToActivate:
      path: /Audio/Machines/button.ogg
      params:
        variation: 0.250
  - type: ItemToggleMeleeWeapon
    activatedDamage:
      types:
        Blunt: 0
  - type: MeleeWeapon
    wideAnimationRotation: -135
    attackRate: 1.5
    damage:
      types:
        Blunt: 7
    bluntStaminaDamageFactor: 2.0
    angle: 60
    animation: WeaponArcSlash
  - type: StaminaDamageOnHit
    damage: 35
    sound: /Audio/Weapons/egloves.ogg
  - type: StaminaDamageOnCollide
    damage: 35
    sound: /Audio/Weapons/egloves.ogg
  - type: LandAtCursor # it deals stamina damage when thrown
  - type: Battery
    maxCharge: 400
    startingCharge: 400
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 5
  - type: UseDelay
  - type: Item
    heldPrefix: off
    size: Normal
  - type: Clothing
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    quickEquip: false
    slots:
    - Belt
  - type: DisarmMalus
    malus: 0.225
  - type: Appearance
  - type: GenericVisualizer
    visuals:
     enum.ToggleVisuals.Toggled:
        enum.ToggleVisuals.Layer:
          True: {state: double_stunbaton_on}
          False: {state: double_stunbaton_off}
  - type: StaticPrice
    price: 200
  - type: Riggable
  - type: SolutionContainerManager
    solutions:
      battery:
        maxVol: 5
  - type: InjectableSolution
    solution: battery
  - type: DrawableSolution
    solution: battery
  - type: Explosive
    explosionType: Default
    intensitySlope: 1.5
    maxIntensity: 200
  - type: PhysicalComposition
    materialComposition:
      Steel: 100
      Plastic: 100
  - type: GuideHelp
    guides:
    - Security
    - Antagonists
