[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –≠–ª–∏–∑–∏—É–º üåë [TTS]"
desc = "–ö–æ—Ä–≤–∞–∫—Å ‚Äî –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–ó–¥–µ—Å—å –ø–æ–º–æ–≥—É—Ç –Ω–æ–≤–∏—á–∫–∞–º!\n–ù–∞ —ç—Ç–æ–º —Å–µ—Ä–≤–µ—Ä–µ –ø–æ–Ω–∏–∂–µ–Ω–Ω—ã–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è –∫ RP.\n–ò–º–µ–µ—Ç—Å—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 180
soft_max_players = 100
map_rotation = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e,tts"
