[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –ù–æ–≤–∞ ü™ê [TTS]"
desc = "[–¢—Ä–µ–±—É–µ—Ç—Å—è 40 —á–∞—Å–æ–≤ –Ω–∞ –¥—Ä—É–≥–æ–º —Å–µ—Ä–≤–µ—Ä–µ Corvax!]\n–ö–æ—Ä–≤–∞–∫—Å ‚Äî –ø–µ—Ä–≤—ã–π —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π –ø—Ä–æ–µ–∫—Ç –≤ Space Station 14.\n–ù–∞ —ç—Ç–æ–º —Å–µ—Ä–≤–µ—Ä–µ –≤—ã—Å–æ–∫–∏–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è –∫ RP.\n–ò–º–µ–µ—Ç—Å—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 120
soft_max_players = 60
map_rotation = false

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 2400
custom_reason = "–î–ª—è –¥–æ—Å—Ç—É–ø–∞ –Ω–∞ —ç—Ç–æ—Ç —Å–µ—Ä–≤–µ—Ä –≤–∞–º –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ—Ç—ã–≥—Ä–∞—Ç—å –Ω–∞ –¥—Ä—É–≥–æ–º —Å–µ—Ä–≤–µ—Ä–µ Corvax –∫–∞–∫ –º–∏–Ω–∏–º—É–º 40 —á–∞—Å–æ–≤."

[rules]
time = 10.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
