[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –í–∞–π—Ç–ª–∏—Å—Ç ‚òï [TTS]"
desc = "–†—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π —Å–µ—Ä–≤–µ—Ä –ø—Ä–æ–µ–∫—Ç–∞ Corvax —Å –¥–æ—Å—Ç—É–ø–æ–º –ø–æ –≤–∞–π—Ç–ª–∏—Å—Ç—É. –î–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è –¥–æ—Å—Ç—É–ø–∞ –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –≤ –Ω–∞—à Discord!"
map_pool = "CorvaxDefaultMapPool"
maxplayers = 80
soft_max_players = 70
map_rotation = true
role_timers = false
peaceful_end = false

[atmos]
space_wind = true

[biomass]
easy_mode = false

[rules]
time = 10.0

[whitelist]
enabled = true

[ic]
flavor_text = true
punctuation = true

[shuttle]
auto_call_time = 0

[hub]
advertise = true
tags = "lang:ru,rp:high,region:eu_e,tts"
